const passages = [
  {
    _id: "wNd1PnDiIN",
    author: "Bob Feller",
    content:
      "Every day is a new opportunity. You can build on yesterday's success or put its failures behind and start over again. That's the way life is, with a new game every day, and that's the way baseball is.",
    tags: ["sports", "competition"],
    authorSlug: "bob-feller",
    length: 200,
    dateAdded: "2022-07-06",
    dateModified: "2022-07-08",
  },
  {
    _id: "vZ-5DQPCJag",
    author: "George Orwell",
    content:
      "Serious sport has nothing to do with fair play. It is bound up with hatred, jealousy, boastfulness, disregard of all rules and sadistic pleasure in witnessing violence. In other words, it is war minus the shooting.",
    tags: ["sports"],
    authorSlug: "george-orwell",
    length: 214,
    dateAdded: "2022-07-06",
    dateModified: "2022-07-08",
  },
  {
    _id: "JIk3cbQ8s",
    author: "Michael Jordan",
    content:
      "I've missed more than 9000 shots in my career. I've lost almost 300 games. 26 times, I've been trusted to take the game winning shot and missed. I've failed over and over and over again in my life. And that is why I succeed.",
    tags: ["sports", "competition", "famous-quotes"],
    authorSlug: "michael-jordan",
    length: 224,
    dateAdded: "2022-07-06",
    dateModified: "2022-07-08",
  },
  {
    _id: "IiQQfTSSTyc",
    author: "Pauline Kael",
    content:
      "Where there is a will, there is a way. If there is a chance in a million that you can do something, anything, to keep what you want from ending, do it. Pry the door open or, if need be, wedge your foot in that door and keep it open.",
    tags: ["motivational"],
    authorSlug: "pauline-kael",
    length: 232,
    dateAdded: "2022-07-06",
    dateModified: "2022-07-06",
  },
  {
    _id: "nZtnCW3_6S",
    author: "Abraham Lincoln",
    content:
      "I am not bound to win, but I am bound to be true. I am not bound to succeed, but I am bound to live by the light that I have. I must stand with anybody that stands right, and stand with him while he is right, and part with him when he goes wrong.",
    tags: ["inspirational", "history", "truth"],
    authorSlug: "abraham-lincoln",
    length: 246,
    dateAdded: "2022-03-12",
    dateModified: "2022-03-12",
  },
  {
    _id: "a86E0FlaTY",
    author: "Alan Watts",
    content:
      "How is it possible that a being with such sensitive jewels as the eyes, such enchanted musical instruments as the ears, and such fabulous arabesque of nerves as the brain can experience itself anything less than a god.",
    tags: ["philosophy"],
    authorSlug: "alan-watts",
    length: 218,
    dateAdded: "2022-03-12",
    dateModified: "2022-03-12",
  },
  {
    _id: "qXO3CA1R5kmS",
    content:
      "Take up one idea. Make that one idea your life - think of it, dream of it, live on that idea. Let the brain, muscles, nerves, every part of your body, be full of that idea, and just leave every other idea alone. This is the way to success.",
    author: "Swami Vivekananda",
    tags: ["success"],
    authorSlug: "swami-vivekananda",
    length: 239,
    dateAdded: "2021-05-12",
    dateModified: "2022-07-04",
  },
  {
    _id: "zbvj3SIQud",
    content:
      "I think people who are creative are the luckiest people on earth. I know that there are no shortcuts, but you must keep your faith in something Greater than you and keep doing what you love. Do what you love, and you will find the way to get it out to the world.",
    author: "Judy Collins",
    tags: ["inspirational"],
    authorSlug: "judy-collins",
    length: 262,
    dateAdded: "2021-05-05",
    dateModified: "2021-06-17",
  },
  {
    _id: "L63tZjtmyQX6",
    content:
      "I'm selfish, impatient and a little insecure. I make mistakes, I am out of control and at times hard to handle. But if you can't handle me at my worst, then you sure as hell don't deserve me at my best.",
    author: "Marilyn Monroe",
    tags: ["famous-quotes"],
    authorSlug: "marilyn-monroe",
    length: 202,
    dateAdded: "2021-04-23",
    dateModified: "2022-01-07",
  },
  {
    _id: "W_NZxqBSuJ",
    content:
      "The friend who can be silent with us in a moment of despair or confusion, who can stay with us in an hour of grief and bereavement, who can tolerate not knowing... not healing, not curing... that is a friend who cares.",
    author: "Henri Nouwen",
    tags: ["friendship"],
    authorSlug: "henri-nouwen",
    length: 218,
    dateAdded: "2021-04-08",
    dateModified: "2021-04-08",
  },
  {
    _id: "01pIIRUUwN",
    content:
      "Knowledge comes, but wisdom lingers. It may not be difficult to store up in the mind a vast quantity of facts within a comparatively short time, but the ability to form judgments requires the severe discipline of hard work and the tempering heat of experience and maturity.",
    author: "Calvin Coolidge",
    tags: ["wisdom"],
    authorSlug: "calvin-coolidge",
    length: 273,
    dateAdded: "2021-03-28",
    dateModified: "2021-03-28",
  },
  {
    _id: "ykXP-CFk_G",
    content:
      "If you're trying to achieve, there will be roadblocks. I've had them; everybody has had them. But obstacles don't have to stop you. If you run into a wall, don't turn around and give up. Figure out how to climb it, go through it, or work around it.",
    author: "Michael Jordan",
    tags: ["wisdom", "inspirational"],
    authorSlug: "michael-jordan",
    length: 248,
    dateAdded: "2021-03-28",
    dateModified: "2021-03-28",
  },
  {
    _id: "PdcCF7bmZfA",
    content:
      "The man who makes everything that leads to happiness depends upon himself, and not upon other men, has adopted the very best plan for living happily. This is the man of moderation, the man of manly character and of wisdom.",
    author: "Plato",
    tags: ["wisdom"],
    authorSlug: "plato",
    length: 222,
    dateAdded: "2021-03-28",
    dateModified: "2021-03-28",
  },
  {
    _id: "J2QOuZPIiG",
    content:
      "You are a product of your environment. So choose the environment that will best develop you toward your objective. Analyze your life in terms of its environment. Are the things around you helping you toward success - or are they holding you back?",
    author: "W. Clement Stone",
    tags: ["wisdom"],
    authorSlug: "w-clement-stone",
    length: 246,
    dateAdded: "2021-03-28",
    dateModified: "2021-03-28",
  },
  {
    _id: "FMZiiLHfCOc",
    content:
      "America's freedom of religion, and freedom from religion, offers every wisdom tradition an opportunity to address our soul-deep needs: Christianity, Judaism, Islam, Buddhism, Hinduism, secular humanism, agnosticism and atheism among others.",
    author: "Parker Palmer",
    tags: ["wisdom", "freedom"],
    authorSlug: "parker-palmer",
    length: 240,
    dateAdded: "2021-03-08",
    dateModified: "2022-07-04",
  },
  {
    _id: "idKyHYiBkP",
    content:
      "I love wisdom. And you can never be great at anything unless you love it. Not be in love with it, but love the thing, admire the thing. And it seems that if you love the thing, and you don't just want to possess it, it will find you.",
    author: "Maya Angelou",
    tags: ["wisdom"],
    authorSlug: "maya-angelou",
    length: 233,
    dateAdded: "2021-03-08",
    dateModified: "2021-03-08",
  },
  {
    _id: "L0xyAdJ40U",
    content:
      "The Universal Zulu Nation stands to acknowledge wisdom, understanding, freedom, justice, and equality, peace, unity, love, and having fun, work, overcoming the negative through the positive, science, mathematics, faith, facts, and the wonders of God, whether we call him Allah, Jehovah, Yahweh, or Jah.",
    author: "Afrika Bambaataa",
    tags: ["wisdom"],
    authorSlug: "afrika-bambaataa",
    length: 302,
    dateAdded: "2021-03-08",
    dateModified: "2021-03-08",
  },
  {
    _id: "8bIHIEuQP5",
    content:
      "The fact is, with every friendship you make, and every bond of trust you establish, you are shaping the image of America projected to the rest of the world. That is so important. So when you study abroad, you're actually helping to make America stronger.",
    author: "Michelle Obama",
    tags: ["friendship"],
    authorSlug: "michelle-obama",
    length: 254,
    dateAdded: "2021-01-19",
    dateModified: "2021-01-19",
  },
  {
    _id: "lxVMQLtBP7",
    content:
      "First we thought the PC was a calculator. Then we found out how to turn numbers into letters with ASCII, and we thought it was a typewriter. Then we discovered graphics, and we thought it was a television. With the World Wide Web, we've realized it's a brochure.",
    author: "Douglas Adams",
    tags: ["technology"],
    authorSlug: "douglas-adams",
    length: 263,
    dateAdded: "2021-01-11",
    dateModified: "2022-01-07",
  },
  {
    _id: "QTf15XLSdB",
    content:
      "I think that we have a great opportunity to impart our wisdom and our knowledge and our experience to this younger generation. It may be different times, but experience transcends time, and wisdom transcends time.",
    author: "Victoria Osteen",
    tags: ["wisdom"],
    authorSlug: "victoria-osteen",
    length: 213,
    dateAdded: "2021-01-11",
    dateModified: "2021-01-11",
  },
  {
    _id: "-93zOmlMP9",
    content:
      "The greatest obstacle to being heroic is the doubt whether one may not be going to prove oneself a fool; the truest heroism is to resist the doubt; and the profoundest wisdom, to know when it ought to be resisted, and when it be obeyed.",
    author: "Nathaniel Hawthorne",
    tags: ["wisdom"],
    authorSlug: "nathaniel-hawthorne",
    length: 236,
    dateAdded: "2021-01-10",
    dateModified: "2021-06-17",
  },
  {
    _id: "IyF7fIZIc3XX",
    content:
      "The most difficult thing is the decision to act, the rest is merely tenacity. The fears are paper tigers. You can do anything you decide to do. You can act to change and control your life; and the procedure, the process is its own reward.",
    author: "Amelia Earhart",
    tags: ["life", "wisdom"],
    authorSlug: "amelia-earhart",
    length: 238,
    dateAdded: "2020-12-17",
    dateModified: "2022-07-04",
  },
  {
    _id: "2EDcr7j6zU",
    content:
      "Wisdom is the right use of knowledge. To know is not to be wise. Many men know a great deal and are all the greater fools for it. There is no fool so great a fool as a knowing fool. But to know how to use knowledge is to have wisdom.",
    author: "Charles Spurgeon",
    tags: ["wisdom"],
    authorSlug: "charles-spurgeon",
    length: 233,
    dateAdded: "2020-10-29",
    dateModified: "2021-06-17",
  },
  {
    _id: "APsci40ULi",
    content:
      "Technology frightens me to death. It's designed by engineers to impress other engineers. And they always come with instruction booklets that are written by engineers for other engineers, which is why almost no technology ever works.",
    author: "John Cleese",
    tags: ["technology"],
    authorSlug: "john-cleese",
    length: 233,
    dateAdded: "2020-09-05",
    dateModified: "2022-01-07",
  },
  {
    _id: "aC9pFlPuapi",
    content:
      "If we are not given the chance to forget, we are also not given the chance to recover our memories, to alter them with time, perspective, and wisdom. Forgetting, we can be ourselves beyond what the past has told us we are; we can evolve. That is the possibility we want from the future.",
    author: "Caterina Fake",
    tags: ["wisdom", "future"],
    authorSlug: "caterina-fake",
    length: 286,
    dateAdded: "2020-08-27",
    dateModified: "2022-07-04",
  },
  {
    _id: "tvXaBe-wkKU",
    content:
      "Sometimes being a friend means mastering the art of timing. There is a time for silence. A time to let go and allow people to hurl themselves into their own destiny. And a time to prepare to pick up the pieces when it's all over.",
    author: "Octavia E. Butler",
    tags: ["friendship"],
    authorSlug: "octavia-e-butler",
    length: 229,
    dateAdded: "2020-07-10",
    dateModified: "2020-07-10",
  },
  {
    _id: "RBidV2o5GA",
    content:
      "Beginning today, treat everyone you meet as if they were going to be dead by midnight. Extend to them all the care, kindness and understanding you can muster, and do it with no thought of any reward. Your life will never be the same again.",
    author: "Og Mandino",
    tags: ["inspirational"],
    authorSlug: "og-mandino",
    length: 239,
    dateAdded: "2020-06-24",
    dateModified: "2020-06-24",
  },
  {
    _id: "KziYFsZxdD",
    content:
      "True friendship multiplies the good in life and divides its evils. Strive to have friends, for life without friends is like life on a desert island... to find one real friend in a lifetime is good fortune; to keep him is a blessing.",
    author: "Baltasar Gracián",
    tags: ["friendship"],
    authorSlug: "baltasar-gracian",
    length: 232,
    dateAdded: "2020-03-15",
    dateModified: "2020-03-15",
  },
  {
    _id: "qrCV1UcPA2",
    content:
      "It is one of the severest tests of friendship to tell your friend his faults. So to love a man that you cannot bear to see a stain upon him, and to speak painful truth through loving words, that is friendship.",
    author: "Henry Ward Beecher",
    tags: ["friendship"],
    authorSlug: "henry-ward-beecher",
    length: 209,
    dateAdded: "2020-03-07",
    dateModified: "2020-03-07",
  },
  {
    _id: "I5zMVI_HGM",
    content:
      "Sometimes I am happy and sometimes not. I am, after all, a human being, you know. And I am glad that we are sometimes happy and sometimes not. You get your wisdom working by having different emotions.",
    author: "Yoko Ono",
    tags: ["wisdom"],
    authorSlug: "yoko-ono",
    length: 200,
    dateAdded: "2020-02-22",
    dateModified: "2020-02-22",
  },
  {
    _id: "8piblkbL7j",
    content:
      "Love is like a friendship caught on fire. In the beginning a flame, very pretty, often hot and fierce, but still only light and flickering. As love grows older, our hearts mature and our love becomes as coals, deep-burning and unquenchable.",
    author: "Bruce Lee",
    tags: ["friendship"],
    authorSlug: "bruce-lee",
    length: 240,
    dateAdded: "2020-02-07",
    dateModified: "2020-02-07",
  },
  {
    _id: "Oi9UJYy-or",
    content:
      "To enjoy good health, to bring true happiness to one's family, to bring peace to all, one must first discipline and control one's own mind. If a man can control his mind, he can find the way to Enlightenment, and all wisdom and virtue will naturally come to him.",
    author: "Buddha",
    tags: ["wisdom"],
    authorSlug: "buddha",
    length: 262,
    dateAdded: "2020-01-26",
    dateModified: "2021-06-17",
  },
  {
    _id: "RFbQKIDffV",
    content:
      "I decided that it was not wisdom that enabled poets to write their poetry, but a kind of instinct or inspiration, such as you find in seers and prophets who deliver all their sublime messages without knowing in the least what they mean.",
    author: "Isocrates",
    tags: ["wisdom"],
    authorSlug: "isocrates",
    length: 236,
    dateAdded: "2020-01-15",
    dateModified: "2020-01-15",
  },
  {
    _id: "bTpqZkd3K7",
    content:
      "Knowledge is going to make you stronger. Knowledge is going to let you control your life. Knowledge is going to give you the wisdom to teach their children. Knowledge is the thing that makes you smile in the face of disaster.",
    author: "Avery Brooks",
    tags: ["wisdom"],
    authorSlug: "avery-brooks",
    length: 225,
    dateAdded: "2019-12-13",
    dateModified: "2019-12-13",
  },
  {
    _id: "psDF8kzy2M",
    content:
      "You are not here merely to make a living. You are here in order to enable the world to live more amply, with greater vision, with a finer spirit of hope and achievement. You are here to enrich the world, and you impoverish yourself if you forget the errand.",
    author: "Woodrow Wilson",
    tags: ["inspirational"],
    authorSlug: "woodrow-wilson",
    length: 257,
    dateAdded: "2019-11-16",
    dateModified: "2019-11-16",
  },
  {
    _id: "SRODo46S0vo",
    content:
      "Experts on romance say for a happy marriage there has to be more than a passionate love. For a lasting union, they insist, there must be a genuine liking for each other. Which, in my book, is a good definition for friendship.",
    author: "Marilyn Monroe",
    tags: ["friendship"],
    authorSlug: "marilyn-monroe",
    length: 225,
    dateAdded: "2019-10-12",
    dateModified: "2019-10-12",
  },
  {
    _id: "JNs1fSaN1K",
    content:
      "Always keep your mind as bright and clear as the vast sky, the great ocean, and the highest peak, empty of all thoughts. Always keep your body filled with light and heat. Fill yourself with the power of wisdom and enlightenment.",
    author: "Morihei Ueshiba",
    tags: ["wisdom"],
    authorSlug: "morihei-ueshiba",
    length: 228,
    dateAdded: "2019-09-23",
    dateModified: "2019-09-23",
  },
  {
    _id: "xAhAKo-kqcD",
    content:
      "Democracy's premise rests on the notion that the collective wisdom of the majority will prove right more often than it's wrong; that given sufficient opportunity in the pursuit of happiness, your population will develop its talents, its intellect, its better judgment; that over time its capacity for discernment and self-correction will be enlarged.",
    author: "Ben Fountain",
    tags: ["wisdom"],
    authorSlug: "ben-fountain",
    length: 350,
    dateAdded: "2019-09-19",
    dateModified: "2019-09-19",
  },
  {
    _id: "gWSsNulTG-B",
    content:
      "Everyone in the world ought to do the things for which he is specially adapted. It is the part of wisdom to recognize what each one of us is best fitted for, and it is the part of education to perfect and utilize such predispositions. Because education can direct and aid nature but can never transform her.",
    author: "Maria Montessori",
    tags: ["wisdom"],
    authorSlug: "maria-montessori",
    length: 307,
    dateAdded: "2019-09-13",
    dateModified: "2021-06-17",
  },
  {
    _id: "iuLrw6KaMA",
    content:
      "As a technology, the book is like a hammer. That is to say, it is perfect: a tool ideally suited to its task. Hammers can be tweaked and varied but will never go obsolete. Even when builders pound nails by the thousand with pneumatic nail guns, every household needs a hammer.",
    author: "James Gleick",
    tags: ["technology"],
    authorSlug: "james-gleick",
    length: 276,
    dateAdded: "2019-09-08",
    dateModified: "2019-09-08",
  },
  {
    _id: "TyDAoeE7hv",
    content:
      "I am not the first Buddha who came upon Earth, nor shall I be the last. In due time, another Buddha will arise in the world - a Holy One, a supremely enlightened One, endowed with wisdom in conduct, auspicious, knowing the universe, an incomparable leader of men, a master of angels and mortals.",
    author: "Buddha",
    tags: ["wisdom"],
    authorSlug: "buddha",
    length: 295,
    dateAdded: "2019-08-08",
    dateModified: "2019-08-08",
  },
  {
    _id: "r2gCpEgG_LP",
    content:
      "And I love that even in the toughest moments, when we're all sweating it - when we're worried that the bill won't pass, and it seems like all is lost - Barack never lets himself get distracted by the chatter and the noise. Just like his grandmother, he just keeps getting up and moving forward... with patience and wisdom, and courage and grace.",
    author: "Michelle Obama",
    tags: ["wisdom"],
    authorSlug: "michelle-obama",
    length: 345,
    dateAdded: "2019-08-03",
    dateModified: "2019-08-03",
  },
  {
    _id: "-UwYfDF1M",
    content:
      "Be Impeccable with Your Word. Speak with integrity. Say only what you mean. Avoid using the word to speak against yourself or to gossip about others. Use the power of your word in the direction of truth and love.",
    author: "Don Miguel Ruiz",
    tags: ["inspirational"],
    authorSlug: "don-miguel-ruiz",
    length: 212,
    dateAdded: "2019-07-23",
    dateModified: "2021-06-17",
  },
  {
    _id: "XbsAE6kO-Q",
    content:
      "Just as treasures are uncovered from the earth, so virtue appears from good deeds, and wisdom appears from a pure and peaceful mind. To walk safely through the maze of human life, one needs the light of wisdom and the guidance of virtue.",
    author: "Buddha",
    tags: ["wisdom"],
    authorSlug: "buddha",
    length: 237,
    dateAdded: "2019-06-13",
    dateModified: "2019-06-13",
  },
  {
    _id: "IXdonGCMtzt_",
    content:
      "It is impossible to escape the impression that people commonly use false standards of measurement, that they seek power, success and wealth for themselves and admire them in others, and that they underestimate what is of true value in life.",
    author: "Sigmund Freud",
    tags: ["success"],
    authorSlug: "sigmund-freud",
    length: 241,
    dateAdded: "2019-04-05",
    dateModified: "2022-07-04",
  },
  {
    _id: "lXx16DT7z2",
    content:
      "In dwelling, live close to the ground. In thinking, keep to the simple. In conflict, be fair and generous. In governing, don't try to control. In work, do what you enjoy. In family life, be completely present.",
    author: "Laozi",
    tags: ["wisdom"],
    authorSlug: "laozi",
    length: 209,
    dateAdded: "2019-04-05",
    dateModified: "2019-04-05",
  },
  {
    _id: "YnDQFxhLNx",
    content:
      "It is time to remember that old wisdom our soldiers will never forget: that whether we are black or brown or white, we all bleed the same red blood of patriots, we all enjoy the same glorious freedoms, and we all salute the same great American Flag.",
    author: "Donald Trump",
    tags: ["wisdom"],
    authorSlug: "donald-trump",
    length: 249,
    dateAdded: "2019-04-05",
    dateModified: "2019-04-05",
  },
  {
    _id: "NiF_deuEUrS",
    content:
      "People usually compare the computer to the head of the human being. I would say that hardware is the bone of the head, the skull. The semiconductor is the brain within the head. The software is the wisdom. And data is the knowledge.",
    author: "Masayoshi Son",
    tags: ["wisdom"],
    authorSlug: "masayoshi-son",
    length: 232,
    dateAdded: "2019-03-15",
    dateModified: "2019-03-15",
  },
  {
    _id: "iXtSYIGVbm",
    content:
      "The strong bond of friendship is not always a balanced equation; friendship is not always about giving and taking in equal shares. Instead, friendship is grounded in a feeling that you know exactly who will be there for you when you need something, no matter what or when.",
    author: "Simon Sinek",
    tags: ["friendship"],
    authorSlug: "simon-sinek",
    length: 272,
    dateAdded: "2019-03-15",
    dateModified: "2019-03-15",
  },
  {
    _id: "lLNouGqzgu",
    content:
      "Be true to yourself, help others, make each day your masterpiece, make friendship a fine art, drink deeply from good books - especially the Bible, build a shelter against a rainy day, give thanks for your blessings and pray for guidance every day.",
    author: "John Wooden",
    tags: ["friendship"],
    authorSlug: "john-wooden",
    length: 247,
    dateAdded: "2019-02-20",
    dateModified: "2019-02-20",
  },
  {
    _id: "fgKMT62j8",
    content:
      "Consult not your fears but your hopes and your dreams. Think not about your frustrations, but about your unfulfilled potential. Concern yourself not with what you tried and failed in, but with what it is still possible for you to do.",
    author: "Pope John XXIII",
    tags: ["inspirational"],
    authorSlug: "pope-john-xxiii",
    length: 233,
    dateAdded: "2019-02-17",
    dateModified: "2019-02-17",
  },
  {
    _id: "yBn9DgK3vf",
    content:
      "A youth, when at home, should be filial and, abroad, respectful to his elders. He should be earnest and truthful. He should overflow in love to all and cultivate the friendship of the good. When he has time and opportunity, after the performance of these things, he should employ them in polite studies.",
    author: "Confucius",
    tags: ["friendship"],
    authorSlug: "confucius",
    length: 303,
    dateAdded: "2019-02-17",
    dateModified: "2019-02-17",
  },
];

export default passages;
